version: '3.8'

services:
  python-app:
    build: .
    ports:
      - "8000:8000"
    # volumes: # .env 파일까지 이미지 빌드 되어 버리는 보안 이슈
    #   - .:/app
    env_file:
      - .env
    networks:
      - app-network
    command: python api.py

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "python-app"
      - "--config"
      - "/etc/ngrok.yml"
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - python-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge