

services:
  building-register:
    build:
      context: .
      dockerfile: Dockerfile  # 생략 가능, 기본값은 'Dockerfile'
    image: sellking-building-register-ui
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    command: python api.py

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "sellking-building-register-ui"
      - "--config"
      - "/etc/ngrok.yml"
    env_file:
      - .env
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - building-register
    networks:
      - app-network

networks:
  app-network:
    driver: bridge